import { Routes } from '@angular/router';

import { FullComponent } from './layouts/full/full.component';

import { AuthLayoutComponent } from './layouts/auth/auth-layout.component';
import { AuthGuard } from './guards/auth.guard';

export const AppRoutes: Routes = [{
  path: '',
  component: FullComponent,
  children: [{
    path: '',
    redirectTo: '/starter',
    pathMatch: 'full',
  }, {
    path: '',
    // loadChildren: './material-component/material.module#MaterialComponentsModule',
    loadChildren: './starter/starter.module#StarterModule',
    canActivate: [AuthGuard]
  }, {
    path: 'starter',
    loadChildren: './starter/starter.module#StarterModule',
    canActivate: [AuthGuard]
  }, {
    path: 'starter/:search',
    loadChildren: './starter/starter.module#StarterModule',
    canActivate: [AuthGuard]
  }, {
    path: 'history',
    loadChildren: './history/history.module#HistoryModule',
    canActivate: [AuthGuard]
  }, {
    path: 'history/:search',
    loadChildren: './history/history.module#HistoryModule',
    canActivate: [AuthGuard]
  }, {
    path: 'marginHistory',
    loadChildren: './history/history.module#HistoryModule',
    canActivate: [AuthGuard]
  }, {
    path: 'marginHistory/:search',
    loadChildren: './history/history.module#HistoryModule',
    canActivate: [AuthGuard]
  }, {
    path: 'request',
    loadChildren: './history/history.module#HistoryModule',
    canActivate: [AuthGuard]
  }, {
    path: 'nac',
    loadChildren: './cm-nacimiento/CMNacimiento.module#CMNacimientoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'nac/:id',
    loadChildren: './cm-nacimiento/CMNacimiento.module#CMNacimientoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'cambioG',
    loadChildren: './cambio-genero/cambioGenero.module#cambioGeneroModule',
    canActivate: [AuthGuard]
  }, {
    path: 'cambioG/:id',
    loadChildren: './cambio-genero/cambioGenero.module#cambioGeneroModule',
    canActivate: [AuthGuard]
  }, {
    path: 'inscripcionT',
    loadChildren: './inscripcion-tardia/inscripcionTardia.module#inscripcionTardiaModule',
    canActivate: [AuthGuard]
  }, {
    path: 'inscripcionT/:id',
    loadChildren: './inscripcion-tardia/inscripcionTardia.module#inscripcionTardiaModule',
    canActivate: [AuthGuard]
  }, {
    path: 'inscripcionT/:id/:judicial',
    loadChildren: './inscripcion-tardia/inscripcionTardia.module#inscripcionTardiaModule',
    canActivate: [AuthGuard]
  }, {
    path: 'adoption',
    loadChildren: './adopcion/adopcion.module#adopcionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'adoption/:id',
    loadChildren: './adopcion/adopcion.module#adopcionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'recForzoso',
    loadChildren: './recForzoso/recForzoso.module#recForzosoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'recForzoso/:id',
    loadChildren: './recForzoso/recForzoso.module#recForzosoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'impugnacionPat',
    loadChildren: './impugnacionPaternidad/impugnacion.module#impugnacionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'impugnacionPat/:id',
    loadChildren: './impugnacionPaternidad/impugnacion.module#impugnacionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'supresionAp',
    loadChildren: './supresionApellido/supresionApellido.module#supresionApellidoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'supresionAp/:id',
    loadChildren: './supresionApellido/supresionApellido.module#supresionApellidoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'def',
    loadChildren: './cm-defuncion/CMDefuncion.module#CMDefuncionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'def/:id',
    loadChildren: './cm-defuncion/CMDefuncion.module#CMDefuncionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'mat',
    loadChildren: './cm-matrimonio/CMMatrimonio.module#CMMatrimonioModule',
    canActivate: [AuthGuard]
  }, {
    path: 'mat/:id',
    loadChildren: './cm-matrimonio/CMMatrimonio.module#CMMatrimonioModule',
    canActivate: [AuthGuard]
  }, {
    path: 'oponentes/:id',
    loadChildren: './cm-matrimonioOponente/CMMatOponente.module#CMMatOponenteModule',
    canActivate: [AuthGuard]
  }, {
    path: 'oponentes/:id/:opposition',
    loadChildren: './cm-matrimonioOponente/CMMatOponente.module#CMMatOponenteModule',
    canActivate: [AuthGuard]
  }, {
    path: 'rec',
    loadChildren: './cm-reconocimiento/CMReconocimiento.module#CMReconocimientoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'rec/:id',
    loadChildren: './cm-reconocimiento/CMReconocimiento.module#CMReconocimientoModule',
    canActivate: [AuthGuard]
  }, {
    path: 'uni',
    loadChildren: './cm-union/CMUnion.module#CMUnionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'uni/:id',
    loadChildren: './cm-union/CMUnion.module#CMUnionModule',
    canActivate: [AuthGuard]
  }, {
    path: 'procedure/:id',
    loadChildren: './procedure/procedure.module#ProcedureModule',
    canActivate: [AuthGuard]
  }, {
    path: 'certificate/:id',
    loadChildren: './certificate/certificate.module#CertificateModule',
    canActivate: [AuthGuard]
  }, {
    path: 'configuration/:type',
    loadChildren: './configuration/configuration.module#ConfigurationModule',
    canActivate: [AuthGuard]
  }, {
    path: 'configuration/:type/:search',
    loadChildren: './configuration/configuration.module#ConfigurationModule',
    canActivate: [AuthGuard]
  }, {
    path: 'marginConfig/:id',
    loadChildren: './configuration/marginals/marginal.module#MarginalModule',
    canActivate: [AuthGuard]
  }, {
    path: 'operatorConfig',
    loadChildren: './configuration/operators/operator.module#OperatorModule',
    canActivate: [AuthGuard]
  }, {
    path: 'operatorConfig/:id',
    loadChildren: './configuration/operators/operator.module#OperatorModule',
    canActivate: [AuthGuard]
  }, {
    path: 'profileConfig',
    loadChildren: './configuration/profiles/profile.module#ProfileModule',
    canActivate: [AuthGuard]
  }, {
    path: 'profileConfig/:id',
    loadChildren: './configuration/profiles/profile.module#ProfileModule',
    canActivate: [AuthGuard]
  }, {
    path: 'volumeConfig',
    loadChildren: './configuration/volumes/volume.module#VolumeModule',
    canActivate: [AuthGuard]
  }, {
    path: 'volumeConfig/:id',
    loadChildren: './configuration/volumes/volume.module#VolumeModule',
    canActivate: [AuthGuard]
  }, {
    path: 'volumeType/:id',
    loadChildren: './configuration/volumeType/volumeType.module#volumeTypeModule',
    canActivate: [AuthGuard]
  }, {
    path: 'marginActa/editData/:procedureTypeCode/:certificateId',
    loadChildren: './marginals/editData/editData.module#editDataModule',
    canActivate: [AuthGuard]
  }, {
    path: 'marginActa/editData/:procedureTypeCode/:certificateId/:procedureId',
    loadChildren: './marginals/editData/editData.module#editDataModule',
    canActivate: [AuthGuard]
  }]
}, {
  path: '',
  component: AuthLayoutComponent,
  children: [{
    path: 'pages',
    loadChildren: './pages/pages.module#PagesModule'
  }]
}, {
  path: '**',
  redirectTo: '/starter'
}
];

